spring.application.name=SpringTest
spring.docker.compose.lifecycle-management=start_and_stop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC